### ISSUE TITLE
[Rule "for-of/for-each"] TypeError: Property alternate of ConditionalExpression expected node to be of a type ["Expression"] but instead got undefined

### ISSUE THREAD

**Issue by inilim** [coderaiser/minify#122]
`TypeError: Property alternate of ConditionalExpression expected node to be of a type ["Expression"] but instead got undefined
    at Object.n [as validate] (file:///E:/other/nvm/v20.11.1/node_modules/minify/node_modules/@putout/minify/bundle/minify.min.js:1:242212)
    at validateField (file:///E:/other/nvm/v20.11.1/node_modules/minify/node_modules/@putout/minify/bundle/minify.min.js:1:315196)
    at validate$2 (file:///E:/other/nvm/v20.11.1/node_modules/minify/node_modules/@putout/minify/bundle/minify.min.js:1:315063)
    at e._replaceWith (file:///E:/other/nvm/v20.11.1/node_modules/minify/node_modules/@putout/minify/bundle/minify.min.js:1:930999)
    at e._remove (file:///E:/other/nvm/v20.11.1/node_modules/minify/node_modules/@putout/minify/bundle/minify.min.js:1:966873)
    at e.remove$w [as remove] (file:///E:/other/nvm/v20.11.1/node_modules/minify/node_modules/@putout/minify/bundle/minify.min.js:1:966287)
    at remove$v.remove (file:///E:/other/nvm/v20.11.1/node_modules/minify/node_modules/@putout/minify/bundle/minify.min.js:1:1023106)
    at fix$9 (file:///E:/other/nvm/v20.11.1/node_modules/minify/node_modules/@putout/minify/bundle/minify.min.js:1:1375147)
    at file:///E:/other/nvm/v20.11.1/node_modules/minify/node_modules/@putout/minify/bundle/minify.min.js:1:1375399
    at tryCatch$6 (file:///E:/other/nvm/v20.11.1/node_modules/minify/node_modules/@putout/minify/bundle/minify.min.js:1:1329304) {
  loc: { line: 910, column: 11 },
  rule: 'for-of/for-each'
}`

![изображение](https://github.com/coderaiser/minify/assets/40324321/b2c1a7f3-f2b5-40a1-bda9-35160d47f9f9)

`  var Le = function t(e) {
      var n = [];
      return e instanceof Map ? e.forEach(function (e, o) {
        var i = e;
        "object" === r(i) && (i = t(i)), n.push([o, i]);
      }) : Object.keys(e).forEach(function (o) { // 910 line
        var i = e[o];
        "object" === r(i) && (i = t(i)), n.push([o, i]);
      }), n;
    }`

![изображение](https://github.com/coderaiser/minify/assets/40324321/0329a853-ef64-45a2-9701-88988cefab51)

**Comment by coderaiser** [comment]
Just fixed with [@putout/minfy v3.9.0](https://github.com/putoutjs/minify/releases/tag/v3.9.0) 🎉. Please re-install **Minify**, is it works for you?
