### ISSUE TITLE
Minifying CodeMirror 6 bundle works in `v9.1.0`, outputs blank file in `v11.2.0`, and throws error in `v11.2.1` up until (and including) latest version

### ISSUE THREAD

**Issue by josephrocca** [coderaiser/minify#128]
Hi, I got this working by downgrading to `v9.1.0` (not that it's possible that a higher version than this works - i.e. the breakage didn't necessarily occur in the version after `v9.1.0` - I haven't binary-searched it), but I figured I'd give a heads up that for this CodeMirror 6 bundle (made with [this repo](https://github.com/RPGillespie6/codemirror-quickstart)):

* https://gist.github.com/josephrocca/7d4ab4b6fa808a285ae93832bd5cfbc5

It works at `v9.1.0`, then at some higher version (which I didn't exactly locate) it starts outputting a blank file (e.g. you can replicate this with `v11.2.0`), and then at `v11.2.1` and up until the latest version it outputs:

```
Error: You passed `path.replaceWith()` a falsy node, use `path.remove()` instead
    at e.replaceWith (file:///home/joe/dev/codemirror6-bundle-test/node_modules/@putout/minify/bundle/minify.min.js:1:833378)
    at MT.replaceWith (file:///home/joe/dev/codemirror6-bundle-test/node_modules/@putout/minify/bundle/minify.min.js:1:886102)
    at __a = __b (file:///home/joe/dev/codemirror6-bundle-test/node_modules/@putout/minify/bundle/minify.min.js:17:25202)
    at file:///home/joe/dev/codemirror6-bundle-test/node_modules/@putout/minify/bundle/minify.min.js:14:644
    at Q$ (file:///home/joe/dev/codemirror6-bundle-test/node_modules/@putout/minify/bundle/minify.min.js:14:915)
    at file:///home/joe/dev/codemirror6-bundle-test/node_modules/@putout/minify/bundle/minify.min.js:14:1366
    at G1 (file:///home/joe/dev/codemirror6-bundle-test/node_modules/@putout/minify/bundle/minify.min.js:10:17527)
    at z4 (file:///home/joe/dev/codemirror6-bundle-test/node_modules/@putout/minify/bundle/minify.min.js:13:15638)
    at z5 (file:///home/joe/dev/codemirror6-bundle-test/node_modules/@putout/minify/bundle/minify.min.js:13:16060)
    at push (file:///home/joe/dev/codemirror6-bundle-test/node_modules/@putout/minify/bundle/minify.min.js:13:18046) {
  loc: { line: 1707, column: 19 },
  rule: 'remove-useless-variables/declaration'
}
```
I'm using this simple command:
```
npx minify ./cm6.bundle.js > ./cm6.bundle.min.js
```

**Comment by coderaiser** [comment]
Could you please provide smallest possible code that reproduces this bug?

**Comment by josephrocca** [comment]
Sure, using the gist I linked above, and using the latest version:
```bash
wget https://gist.githubusercontent.com/josephrocca/7d4ab4b6fa808a285ae93832bd5cfbc5/raw/19780f4ed1642c606c919ae1d0374e1bcb95f9b1/cm6.bundle.js
npm install minify
npx minify ./cm6.bundle.js > ./cm6.bundle.min.js
```
This reproduces the `Error: You passed `path.replaceWith()` a falsy node, use `path.remove()` instead` error (I just tested again to ensure I reproduces). If you'd like to reproduce the "outputs blank file" error, you can `npm install minify@11.2.0`).

**Comment by coderaiser** [comment]
I’m talking about code example, 10 lines maximum, not the full bundle. About empty file, looks like there is variable that not used, so it is removed. You can create `.minify.json` with:

```js
{
    "js": {
        "type": "putout",
        "putout": {
           "removeUnusedVariables": false,
        }
    }
}
```

**Comment by coderaiser** [comment]
Something like this, would be very good:

```js
let newVal, oldAddr = oldState.config.address[id];
if (oldAddr != null) {
   let oldVal = getAddr(oldState, oldAddr);
   if (this.dependencies.every(dep => {
       return dep instanceof Facet ? oldState.facet(dep) === state.facet(dep) :
           dep instanceof StateField ? oldState.field(dep, false) == state.field(dep, false) : true;
   }) || (multi ? compareArray(newVal = getter(state), oldVal, compare) : compare(newVal = getter(state), oldVal))) {
       state.values[idx] = oldVal;
       return 0;
   }
}
else {
   newVal = getter(state);
}
state.values[idx] = newVal;
```

**Comment by coderaiser** [comment]
Just fixed, please re-install **Minify**.

**Comment by coderaiser** [comment]
This 3 lines reproduction doesn’t helpful at all, please share short peace of code instead next time.
[`@putout/minify`](https://www.npmjs.com/package/@putout/minify) is direct dependency of **Minify**, is couple hours like in npm.

**Comment by josephrocca** [comment]
> This 3 lines reproduction doesn’t helpful at all, please share short peace of code instead next time.

I thought it was pretty clear in my original issue that I wasn't asking for your help:

> I got this working [...] but I figured I'd give a heads up

I do my best to help open source projects, and regularly spend multiple days to help a project fix something, but sometimes I don't have time to dig in and debug for them, especially if there are alternative projects which work fine. For context, I actually ended up switching to the rollup terser plugin, but figured before I `npm uninstall minify` I should be a good open source citizen at least let you know about the bug instead of just shrugging and moving on. I was simply sharing some information in case it was helpful to your project.

I have a *lot* of respect for open source maintainers like yourself, but please don't chastise people when they simply try to help your project, or feel entitled to their time when they are simply letting you know about a problem and **explicitly not asking for your help**. Again, I think it was pretty clear from my original post that I wasn't asking for your help - I was trying to help the project. For issues like this, you should **just close the issue** if it's not helpful.

(As an aside, the 3-line reproduction obviously *is* useful as an existence check for the bug, if nothing else. So your comment comes off as somewhat flippant.)

**Comment by coderaiser** [comment]
Thank you for you help of providing me 1MB file that errored, instead of 10 lines of code, and didn’t checked if the fix works. This is really helps to maintain Open Source 👍 Maintainers have much more time then you and it costs much less then yours.

**Comment by josephrocca** [comment]
> didn’t checked if the fix works

I gave you a 3-line code snippet to check this. About 2 seconds to paste that in your terminal. And despite that, I did try to do that for you, but I think you want me to build your project from source or something? When I've told you that I'm not even using your project, and am just posting to *let you know* about the issue?

Here, let me remind you:

> For context, I actually ended up switching to the rollup terser plugin, but figured before I `npm uninstall minify` I should be a good open source citizen at least let you know about the bug instead of just shrugging and moving on.

Here's what you can say next time, if you'd like to seem like a decent person and/or adult:

> Hmm, I'm not sure what could be causing that. I'll probably need more details or a more minimal example if I were to be able to make the time to fix this.

Or you can just close the issue. Snarky comments don't help anyone. If you're trying to guilt people into putting more time into helping your project, it's not not a good strategy. Just politely close issues that aren't actionable. Being an open source maintainer doesn't give you a license to be rude to people who are genuinely and kindly trying to help your project, even if a bug report turns out to not be that useful in the end.

**Comment by coderaiser** [comment]
I see that you just don’t understand how minifiers works, just read this:

https://github.com/jamiebuilds/the-super-tiny-compiler

And you will understand that 1MB file becomes very-very-very big AST-tree, and that’s not helpful at all. Thank you for you report, would be great if you finish work, and check config I provided and fix, because it takes time, and Open Source it’s not just put 1MB file and do whatever you want, it’s taking responsibility in finishing work on issue and trying everything maintainers tell you while the problem will be fixed. 

And much better if you fix this by yourself and send PR, half backed issue is so-so 🤷. But anyways, thank you, I fixed 🐊**Putout** plugin, and I’m happy with this.
