### ISSUE TITLE
error on minifying multiple files

### ISSUE THREAD

**Issue by Mantou1233** [coderaiser/minify#129]
```
$ minify ongeki/src/js/*.js > ongeki/ongeki-functions.js
Error: ENOENT: no such file or directory, open 'D:\0P\otoge-db\ongeki\src\js\*.js'
    at async open (node:internal/fs/promises:639:25)
    at async readFile (node:internal/fs/promises:1249:14)
    at async optimize (D:\0P\otoge-db\node_modules\minify\lib\minify.js:60:18)
    at async minify (D:\0P\otoge-db\node_modules\minify\lib\minify.js:35:12)
    at async Promise.all (index 0) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\0P\\otoge-db\\ongeki\\src\\js\\*.js'
}
```
why wouldnt this syntax work? afaik it works on others

**Comment by coderaiser** [comment]
Globs not supported, but this good idea for a PR

**Comment by coderaiser** [comment]
Do you want all globs was joined in final bundle?

**Comment by Mantou1233** [comment]
yes it is only supported on linux rn

**Comment by coderaiser** [comment]
Linux and Mac works good, and Windows not? Are you up for a PR?

**Comment by coderaiser** [comment]
Closed due to a long time of inactivity 🏝
